### ISSUE TITLE
does not build OOTB

### ISSUE THREAD

**Issue by itmo** [TheFinnishSocialInsuranceInstitution/KantaCDA-API#2]
missing repository for log4j 2.1 stuff, log4j-core is refererred to as "2.1.0" although "2.1" is the correct (?!?) published version, also bindings contain windows paths , which prevent building on other (normal) operating systems. I suggest adding an automatic build pipeline.

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
An automatic build pipeline exists in Kela, and the code builds normally there (Jenkins running on Linux). However, our Nexus has a version 2.1.0 of this library available, perhaps it was introduced manually at some point. Will review this dependency.

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
@itmo thank you for indicating the Windows paths in bindings. Which operating system do you use? So far, we have not faced problems with them (schemaLocation="..\Schemas\POCD_MT000040_Fi.xsd") on Windows on Linux. Will change the path anyway.

**Comment by itmo** [comment]
Thats why there should also be  a basic build pipeline AFTER publishing the code. I use Fedora 25.

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
Fixed.
