### ISSUE TITLE
contains stupid bugs,discoverable with static analysis

### ISSUE THREAD

**Issue by itmo** [TheFinnishSocialInsuranceInstitution/KantaCDA-API#3]
Please run findbugs.. 
MaarittelyKonfiguraatio.java line 110 has a potential nullpointer dereference since line 107 is
"    if ( (token == null) && "".equals(token) ) {" , should probably be "||" or SomeUtils.isEmpty(token)

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
Thank you for noting this bug. It was in fact introduced after running static analysis and reviewing the code, after a suggestion to improve readability of this chunk of code. Sometimes improvements lead to new bugs :) This will be fixed.

**Comment by itmo** [comment]
and this is why you should run static analysis all the time and not just on special days. (there are 55 more findbug hits in there)

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
Fixed.
