### ISSUE TITLE
Is the git repository master for development or a published (dead) branch?

### ISSUE THREAD

**Issue by mikko-apo** [TheFinnishSocialInsuranceInstitution/KantaCDA-API#4]
I think it would be very useful if the readme explains following things:

- If this repository is the master for future development of the project or if the development is done elsewhere. 
- Does the owner accept Pull Requests or Issues. If this repository is not the master, how and when changes from this repository are moved to the master.
- How the project is maintained and how it's going to be developed (and access to backlog?)

.. For example, I could make a Pull Request that fixes the build related bugs and adds travis-ci build that verifies that the build works. If the owner doesn't accept changes to the master I can't contribute to the project.

**Comment by TheFinnishSocialInsuranceInstitution** [comment]
It is neither the former nor the latter. This is a fork (stream) of Kela's internal version control system. This is not a dead branch, and we plan to make new versions available from time to time. Pull requests are accepted and will be considered for integration after review in the internally maintained version system. This is not a fully open public software development project, but we make the source available to those interested in it, and are happy for information on bugs or improvement suggestions. Forks may be made freely and the source code may also be developed elsewhere, if someone wants to establish a more open community. The project is actively maintained in Kela as part of Omakanta and Kelain development and maintenance projects.
